### PR TITLE
support for clone

### PR DESCRIPTION
**Pull request by Misiu**
This adds support for Clone - this will create a new client without the need to do extra requests to get WSDL definitions (which can take significant amount of time).
I've added support for IDisposable to OnPremiseClient, so we can dispose the object (I'm not sure if we need to dispose any internal resources)
I've cleaned LINQ to remove extra methods, for example I use SingleOfDefault instead of Where and SingleOfDefault.

### CODE REVIEW

**Comment by MarkMpn** [comment]
Thanks for the PR! I think the principle is sound, but there are a few things I'd like to clarify:

I'm not clear on the purpose of adding `IDispose` here - there aren't any unmanaged resources to dispose of.

There's a potential for threading issues with reusing the `_innerService` instances. In particular the `ADAuthClient` uses instance variables to store the authentication tokens and there's a possible race condition if two threads trigger a re-authentication after the initial token expires - this could do with a lock being introduced in the `ADAuthClient.Authenticate` method.

I also haven't tested the behaviour with multiple concurrent calls. Looking at the `ADAuthClient` I believe each request should be sent immediately, but with the `ClaimsBasedAuthClient` it's hidden in the depths of WCF - would the requests be sent in parallel or serialized? It would be good to see the results of a test where you have several parallel tasks executing requests that should take a second each - do the results come back at the same time or do they finish one at a time with a second between them?

**Comment by Misiu** [comment]
Thank You for such fast reply.
I agree that IDisposable isn't needed if there are no resources that must be explicit disposed.
I'm already working on cloning of ADAuthClient, this will ensure that each cloned client will get new instance. Not sure if this is needed, maybe a lock would be better and ADAuthClient should be shared in all instances. Any, suggestions?

I have a test server and I'm able to test ADAuthClient, but sadly no way to test ClaimsBasedAuthClient.

**Comment by Misiu** [comment]
@MarkMpn is there anything else I should change/test? Can you test `ClaimsBasedAuthClient`?

**Comment by Misiu** [comment]
Thank you for the reply. I'll try to do some more cleanup and test everything with .NET 8

**Comment by Misiu** [comment]
I have one more change here. I'll be at my PC in an hour or so.

**Comment by Misiu** [comment]
My local changes are almost identical to those in your change.
So I won't push anything new here.

With this one merged I'll rebase my next PR, it cleans the code even more.

**Pull request merged**
