### PR TITLE
Net8 + remove InnerService and AsyncWrapper + implement IOrganizationServiceAsync2 in ClaimsBasedAuthClient

### PR DESCRIPTION
**Pull request by Misiu**

### CODE REVIEW

**Comment by Misiu** [comment]
@MarkMpn this adds .NET8 as a target and eliminates OrgServiceAsyncWrapper and _innerService.
I've also added async and await to all the methods that previously returned Task or Task<T>, which makes this library closer to https://github.com/microsoft/PowerPlatform-DataverseServiceClient

**Comment by MarkMpn** [comment]
I've just pushed a few changes, the most significant being to the target frameworks. I've removed net472 and net48 as there's no difference to the compiled package compared to net462, and similar for net8.0 vs. net7.0. I've also replaced netcoreapp3.1 with net6.0 to synchronize with the latest version of Microsoft.PowerPlatform.Dataverse.Client.

Let me know if there's a specific reason you need it packaged directly for .NET 8 rather than using the version built for .NET 7.

**Comment by Misiu** [comment]
I've added .NET8 to test everything in my dev project.
Your changes look good, I forgot to bump dependencies, but with those changes we are up-to-date.

I'll try to do more cleanup in the following PRs and add some documentation on using this library in ASP.NET Core projects (now we can Clone client).

I was looking at how Entity Framework is creating context pooling and tried to create a similar approach, but this probably should be a separate package because of dependencies unrelated to the main project.

**Comment by Misiu** [comment]
@MarkMpn I've tested ADAuthClient. If you can test ClaimsBasedAuthClient then we can merge this.

**Comment by MarkMpn** [comment]
I've just pushed another change which should make cloning an AD-authenticated client more efficient by reusing the existing security token instead of going through the SSPI steps again, can you retest with this update please?

**Comment by Misiu** [comment]
@MarkMpn I've fixed two not-implemented methods. I used Async versions, but then all Async operations thow exceptions:
image

image

I'll do some operations on my test system and comment with the results.

**Comment by Misiu** [comment]
@MarkMpn I've refactored tests a bit, I've moved ClaimsBasedAuthClient test into a separate file.
It will be easier to add new tests in the future.
I've also used this branch in my dev project, and the basic operations (CRUD) work fine.

If there is something else I should look at please let me know 🙂

**Pull request merged**
